/*
Drop table related PostgreSQL queries.

Purpose of this file:
- Create tables
- Create a relationship between tables using a foreign key
- Drop a table safely
- Show the current tables

Commands used in this file and their purpose:
- CREATE TABLE: creates a table in the selected database
- FOREIGN KEY: links one table to another table
- DROP TABLE: removes a table and all its data permanently
- IF EXISTS: prevents errors if the table does not exist
- pg_tables: shows tables in the current database

Important note:
- DROP TABLE removes the table structure and all data inside it.
- If a table is referenced by a foreign key, drop the child table first.
*/

-- Create the parent table
CREATE TABLE IF NOT EXISTS demo_table (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    description VARCHAR(255)
);

-- Create the child table
CREATE TABLE IF NOT EXISTS demo_details (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demo_id INTEGER,
    detail VARCHAR(255),
    CONSTRAINT fk_demo_details_demo_table
        FOREIGN KEY (demo_id) REFERENCES demo_table(id)
);

-- Show the current tables in the public schema
SELECT tablename
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;

-- Drop the child table first
DROP TABLE IF EXISTS demo_details;

-- Show tables again
SELECT tablename
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;

-- Drop the parent table
DROP TABLE IF EXISTS demo_table;

-- Show tables again after dropping the parent table
SELECT tablename
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;

/*
Example notes:
- If you try to drop demo_table before demo_details, PostgreSQL may block it
  because demo_details depends on demo_table through the foreign key.
- To remove the whole database completely, use:
  DROP DATABASE IF EXISTS company;
*/