/*
Simple PostgreSQL guide for creating tables, inserting records, and viewing data.

Purpose of this file:
- Create a database
- Use the database
- Create tables
- Insert sample data
- Show table structure
- Show stored data

Commands used in this file and their purpose:
- CREATE TABLE: creates a new table
- PRIMARY KEY: identifies each row uniquely
- NOT NULL: prevents empty values in a column
- UNIQUE: ensures values in a column are different
- FOREIGN KEY: links one table to another
- INSERT INTO ... VALUES: adds new rows to a table
- SELECT: reads data from one or more tables

How to use this file:
1. Make sure PostgreSQL is running.
2. Create the database first, for example:
   createdb company
3. Connect to the database.
4. Run the queries from top to bottom.
*/

-- Create the employer table
CREATE TABLE IF NOT EXISTS employer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    phone_number VARCHAR(15),
    email VARCHAR(100) UNIQUE,
    established_date DATE,
    industry VARCHAR(50)
);

-- Create the employee table
CREATE TABLE IF NOT EXISTS employee (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_id INTEGER,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    position VARCHAR(50),
    salary NUMERIC(10, 2) DEFAULT 0.00,
    hire_date DATE,
    CONSTRAINT fk_employee_employer
        FOREIGN KEY (employer_id) REFERENCES employer(id)
);

-- Insert sample data into employer table
INSERT INTO employer (name, address, phone_number, email, established_date, industry)
VALUES
    ('Tech Solutions Inc.', '123 Tech Street, Silicon Valley, CA', '123-456-7890', 'info@techsolutions.com', '2020-01-01', 'Technology'),
    ('Green Energy Corp.', '456 Green Avenue, Austin, TX', '987-654-3210', 'info@greenenergy.com', '2019-06-15', 'Renewable Energy');

-- Insert sample data into employee table
INSERT INTO employee (employer_id, first_name, last_name, position, salary, hire_date)
VALUES
    (1, 'John', 'Doe', 'Software Engineer', 75000.00, '2020-01-15'),
    (1, 'Jane', 'Smith', 'Project Manager', 85000.00, '2020-03-20'),
    (2, 'Bob', 'Johnson', 'Energy Consultant', 65000.00, '2019-07-10'),
    (2, 'Alice', 'Williams', 'Sustainability Specialist', 70000.00, '2019-09-25');

-- Show all tables in the current schema
SELECT tablename
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;

-- Show the structure of the tables
SELECT * FROM employer;
SELECT * FROM employee;

-- Show selected columns only
SELECT first_name, last_name, position FROM employee;
SELECT name, email FROM employer;

-- Example: create a department table from employer industries
CREATE TABLE IF NOT EXISTS department AS
SELECT DISTINCT industry AS department_name
FROM employer;

-- Show the new table
SELECT * FROM department;